#!/bin/bash

SCRIPT_PATH="$( cd "$(dirname "$0")" ; pwd -P )"
SCRIPT_PATH="$(realpath $SCRIPT_PATH)"

[ -d ${HOME}/.local/bin ] || mkdir -p ${HOME}/.local/bin
cp ${SCRIPT_PATH}/kitty-control ${HOME}/.local/bin/kitty-control
chmod 755 ${HOME}/.local/bin/kitty-control

[ -d ${HOME}/.config/kitty ] || mkdir -p ${HOME}/.config/kitty
cp ${SCRIPT_PATH}/kitten/read_config.py ${HOME}/.config/kitty
chmod 644 ${HOME}/.config/kitty/read_config.py

[ "${KITTY_CONFIG_DIRECTORY}" ] && {
  [ "${KITTY_CONFIG_DIRECTORY}" == "${HOME}/.config/kitty" ] || {
    [ -d "${KITTY_CONFIG_DIRECTORY}" ] && {
      cp ${SCRIPT_PATH}/kitten/read_config.py ${KITTY_CONFIG_DIRECTORY}
      chmod 644 ${KITTY_CONFIG_DIRECTORY}/read_config.py
    }
  }
}

printf "Installation of kitty-control complete ✨ 🌟 ✨\n"
printf "\nSee https://github.com/doctorfree/kitty-control#readme\n\n"
