#!/bin/bash
#  __ _  __  ____  ____  _  _       ___  __   __ _  ____  ____   __   __
# (  / )(  )(_  _)(_  _)( \/ )___  / __)/  \ (  ( \(_  _)(  _ \ /  \ (  )
#  )  (  )(   )(    )(   )  /(___)( (__(  O )/    /  )(   )   /(  O )/ (_/\
# (__\_)(__) (__)  (__) (__/       \___)\__/ \_)__) (__) (__\_) \__/ \____/
#
# kitty-control - control the Kitty terminal emulator from the command line
#
# Written Feb 1, 2024 by Ronald Joe Record <ronaldrecord@gmail.com>
#
VERSION=1.0.1
RELEASE=5
# The Kitty configuration directory
CONFDIR="${HOME}/.config/kitty"
[ "${KITTY_CONFIG_DIRECTORY}" ] && {
  [ -f "${KITTY_CONFIG_DIRECTORY}/kitty.conf" ] && {
    CONFDIR="${KITTY_CONFIG_DIRECTORY}"
  }
}
# The default background opacity for transparency
OPACITY="0.8"
# The socket Kitty is listening on if configured
# The format of this setting is:
#   SOCKET="--to unix:/path/to/socket"
# Leave blank if no listen socket configured
# Can be overridden with -s /path/to/socket
if [ "${KITTY_LISTEN_ON}" ]; then
    SOCKET="--to ${KITTY_LISTEN_ON}"
else
  SOCKET=
fi
# Kitty remote control options are used to specify which windows/tabs to modify
OPTS=
# Menu system vars
FONTDIR="${HOME}/.local/share/figlet-fonts"
LOLCAT="lolcat"
# Array with font names
fonts=("Fire Font-k" "Graceful" "Script" "Shadow" "Slant" "Small" "Standard")
# Use tput to get the bold and normal text sequence
BOLD=$(tput bold 2>/dev/null)
NORM=$(tput sgr0 2>/dev/null)

brief_usage() {
  printf "${BOLD}Usage: kitty-control [-a] [-c command] [dark] [-e] [-f] [-i /path/to/image]"
  printf "\n    [-m|t <match>] [-s /path/to/socket] [-u|h|v] [back <color>] [term] [theme]"
  printf "\n    [diff [opts] <path1> <path2>] [fore <color>] [font [num]] [load [subdir]]"
  printf "\n    [icat [opts] <image>] [list] [menu] [title <title>] [tran [opacity]]"
  printf "\n    [unicode] [upgrade]${NORM}"
  [ "$1" == "noexit" ] || {
    printf "\n\nTo display several examples run 'kitty-control -e'"
    printf "\nFor a full usage message run 'kitty-control -u'"
    printf "\nFor a full usage message with examples run 'kitty-control -h'\n\n"
    exit 1
  }
}

show_examples() {
  brief_usage noexit
  printf "\nExample invocations of kitty-control\n"
  printf "\nTo set a transparent Kitty background with 0.9 opacity:"
  printf "\n\t${BOLD}kitty-control tran 0.9${NORM}"
  printf "\nTo set the Kitty background to fully opaque (no transparency):"
  printf "\n\t${BOLD}kitty-control dark${NORM}"
  printf "\nTo set the Kitty background color to black and foreground color to white:"
  printf "\n\t${BOLD}kitty-control back black fore white${NORM}"
  printf "\nTo load the Kitty config in ~/.config/kitty/laptop/kitty.conf"
  printf "\n\t${BOLD}kitty-control load laptop${NORM}"
  printf "\nTo increase the font size by 2 points:"
  printf "\n\t${BOLD}kitty-control font +2${NORM}"
  printf "\nTo set the background image to ~/Pictures/groovy.png"
  printf "\n\t${BOLD}kitty-control -i ~/Pictures/groovy.png${NORM}"
  printf "\nActions can be combined on the same command line:"
  printf "\n\t${BOLD}kitty-control -i ~/Pictures/groovy.png fore cyan font 24${NORM}"
  printf "\nTo view the image ~/Pictures/cats.png"
  printf "\n\t${BOLD}kitty-control icat ~/Pictures/cats.png${NORM}"
  printf "\nTo view differences between /path/to/file1 and /path/to/file2"
  printf "\n\t${BOLD}kitty-control diff /path/to/file1 /path/to/file2${NORM}"
  printf "\nTo set the tab title of the tab currently titled '~/src/borg' to 'Borg Backup':"
  printf "\n\t${BOLD}kitty-control -m \"title:borg\" title \"Borg Backup\"${NORM}"
  printf "\nTo restore the original Kitty configuration:"
  printf "\n\t${BOLD}kitty-control load default${NORM}\n"
  exit 1
}

usage() {
  brief_usage noexit
  printf "\nWhere:"
  printf "\n    '${BOLD}back color${NORM}' Sets the background color to 'color'"
  printf "\n           If 'color' is 'reset' restores foreground and background to startup value"
  printf "\n    '${BOLD}dark${NORM}' Sets the Kitty background opacity to 1.0 (fully opaque)"
  printf "\n           Can use 'dark' or 'opaque'"
  printf "\n    '${BOLD}diff [opts] <file1|dir1> <file2|dir2>${NORM}'"
    printf " Displays differences using the 'diff' kitten"
  printf "\n           Enclose [opts] and <file1/dir1> in quotes if [opts] are provided"
  printf "\n           See https://sw.kovidgoyal.net/kitty/kittens/diff/#options"
  printf "\n    '${BOLD}font num${NORM}' Sets the font pointsize to 'num'"
  printf "\n           Can use 'font', 'fontsize', 'fontminus', or 'fontplus'"
  printf "\n           The second argument specifies the font size, either absolute, +, or -"
  printf "\n           e.g. 'kitty-control fontsize 24' would set the font size to 24 points"
  printf "\n                'kitty-control font +2' would increase the font size by 2 points"
  printf "\n                'kitty-control font' without argument resets the font size to default"
  printf "\n    '${BOLD}fore color${NORM}' Sets the foreground color to 'color'"
  printf "\n           If 'color' is 'reset' restores foreground and background to startup value"
  printf "\n    '${BOLD}icat [opts] <image>${NORM}' Displays <image> using the Kitty 'icat' kitten"
  printf "\n           Enclose [opts] and <image> in quotes if [opts] are provided"
  printf "\n           To remove all images currently displayed on the screen:"
  printf "\n               kitty-control icat --clear"
  printf "\n           See https://sw.kovidgoyal.net/kitty/kittens/icat/#options"
  printf "\n    '${BOLD}list${NORM}' Displays information on Kitty windows"
  printf "\n    '${BOLD}load [subdir]${NORM}'"
    printf " Reloads the Kitty configuration in ~/.config/kitty/kitty.conf"
  printf "\n           Can use 'load' or 'reload'"
  printf "\n           Specify a second argument to load ~/.config/kitty/<subdir>/kitty.conf"
  printf "\n           e.g. 'kitty-control load tv' would load ~/.config/kitty/tv/kitty.conf"
  printf "\n           'kitty-control load default' loads the ~/.config/kitty/kitty.conf config"
  printf "\n           'kitty-control load --help' displays a help message for the load command"
  printf "\n    '${BOLD}menu${NORM}' Displays the kitty-control interactive menu system"
  printf "\n    '${BOLD}term${NORM}'"
    printf " Displays information about the terminal using the query_terminal kitten"
  printf "\n    '${BOLD}theme${NORM}' Displays the interactive theme selection kitten"
  printf "\n    '${BOLD}title <tab title>${NORM}' Sets the Kitty tab title to \"tab title\""
  printf "\n          Quote tab titles which contain spaces, e.g. \"This Is My Tab Title\""
  printf "\n          Use '-m <match>' to specify the tab to match"
  printf "\n    '${BOLD}tran [opacity]${NORM}' Sets the Kitty background opacity to 0.8"
  printf "\n           Can use 'tran', 'opacity', 'trans' or 'transparent'"
  printf "\n           Specify a second argument to set a custom background opacity:"
  printf "\n           e.g. 'kitty-control transparent 0.9'"
  printf "\n    '${BOLD}unicode${NORM}' Displays the Unicode input kitten"
  printf "\n    '${BOLD}upgrade${NORM}' Upgrades Kitty to the latest version"
  printf "\n    '${BOLD}-a${NORM}'"
    printf " Indicates modify all windows rather than just the currently active OS window"
  printf "\n    '${BOLD}-c command${NORM}'"
    printf " specifies a Kitty command to run (enclose command and arguments in quotes)"
  printf "\n        Can be used to run arbitrary commands, e.g. 'kitty-control -c get-colors'"
  printf "\n    '${BOLD}-e${NORM}' Displays several example invocations and exits"
  printf "\n    '${BOLD}-f${NORM}' Indicates toggle fullscreen"
  printf "\n    '${BOLD}-h${NORM}' Displays the usage message with examples and exits"
  printf "\n    '${BOLD}-i /path/to/image${NORM}'"
    printf " sets the background image for the specified Kitty windows"
  printf "\n        If /path/to/image is 'none' then any existing image will be removed"
  printf "\n    '${BOLD}-m <match>${NORM}' Specifies the window to match"
  printf "\n    '${BOLD}-t <match>${NORM}' Specifies the tab to match"
  printf "\n        Window/Tab matching can be used in conjunction with most kitty-control commands"
  printf "\n        If <match> is '--help' the Kitty documentation URL for matching will be displayed"
  printf "\n    '${BOLD}-s /path/to/socket${NORM}'"
    printf " Specifies the socket Kitty is listening on if enabled"
  printf "\n        If /path/to/socket is '--help' some help on configuring a Kitty socket is provided"
  printf "\n        '-s /path/...' can be used to send commands to Kitty from another terminal"
  printf "\n    '${BOLD}-u${NORM}' Displays the usage message and exits"
  printf "\n    '${BOLD}-v${NORM}' Displays the kitty-control version and exits"
  printf "\nAdjusting the background opacity or font size requires the original kitty.conf"
  printf "\nthat was used for this instance of Kitty to have enabled the following:"
  printf "\n    '${BOLD}dynamic_background_opacity yes${NORM}'"
    printf " and '${BOLD}allow_remote_control yes${NORM}'"
  printf "\nSee https://sw.kovidgoyal.net/kitty/remote-control/#control-kitty-from-scripts\n"
  [ "$1" == "examples" ] && show_examples
  exit 1
}

kitty-fontminus() {
  size="$1"
  first_size=${size::1}
  if [[ "${first_size}" == "-" ]]; then
    kitty @ ${SOCKET} set-font-size ${OPTS} -- $size
  else
    kitty @ ${SOCKET} set-font-size ${OPTS} -- -$size
  fi
}

kitty-fontplus() {
  size="$1"
  first_size=${size::1}
  if [[ "${first_size}" == "+" ]]; then
    kitty @ ${SOCKET} set-font-size ${OPTS} $size
  else
    kitty @ ${SOCKET} set-font-size ${OPTS} +$size
  fi
}

kitty-fontsize() {
  size="$1"
  first_size=${size::1}
  if [[ "${first_size}" == "-" ]]; then
    kitty @ ${SOCKET} set-font-size ${OPTS} -- $size
  else
    kitty @ ${SOCKET} set-font-size ${OPTS} $size
  fi
}

set-background() {
  if [ "$1" == "reset" ]; then
    kitty @ ${SOCKET} set-colors ${OPTS} --reset
  else
    kitty @ ${SOCKET} set-colors ${OPTS} background=$1
  fi
}

set-foreground() {
  if [ "$1" == "reset" ]; then
    kitty @ ${SOCKET} set-colors ${OPTS} --reset
  else
    kitty @ ${SOCKET} set-colors ${OPTS} foreground=$1
  fi
}

set-opacity() {
  kitty @ ${SOCKET} set-background-opacity ${OPTS} $1
}

toggle-fullscreen() {
  kitty @ ${SOCKET} resize-os-window --action toggle-fullscreen ${OPTS}
}

install_kitty() {
  LOCAL=".local/kitty.app"
  printf "\n\tInstalling/Upgrading Kitty terminal emulator ..."
  curl --silent --location \
    https://sw.kovidgoyal.net/kitty/installer.sh >/tmp/kitty-$$.sh
  [ $? -eq 0 ] || {
    rm -f /tmp/kitty-$$.sh
    curl --insecure --silent --location \
      https://sw.kovidgoyal.net/kitty/installer.sh >/tmp/kitty-$$.sh
    cat /tmp/kitty-$$.sh | sed -e "s/curl -/curl -k/" >/tmp/k$$
    cp /tmp/k$$ /tmp/kitty-$$.sh
    rm -f /tmp/k$$
  }
  if [ -s /tmp/kitty-$$.sh ]; then
    sh /tmp/kitty-$$.sh launch=n >/dev/null 2>&1
    rm -f /tmp/kitty-$$.sh
    # Create a symbolic link to add kitty to PATH
    [ -d ~/.local/bin ] || mkdir -p ~/.local/bin
    if [ -x ~/${LOCAL}/bin/kitty ]; then
      [ -x ~/.local/bin/kitty ] || {
        ln -s ~/${LOCAL}/bin/kitty ~/.local/bin/
      }
    else
      printf "\nUnable to create Kitty link to ~/.local/bin/\n"
    fi
    if [ -x ~/${LOCAL}/bin/kitten ]; then
      [ -x ~/.local/bin/kitten ] || {
        ln -s ~/${LOCAL}/bin/kitten ~/.local/bin/
      }
    else
      printf "\nUnable to create kitten link to ~/.local/bin/\n"
    fi
    # Link the kitty man pages somewhere it can be found by the man command
    LINMAN="${HOME}/${LOCAL}/share/man"
    [ -d ~/.local/share/man/man1 ] || mkdir -p ~/.local/share/man/man1
    [ -f ~/.local/share/man/man1/kitty.1 ] || {
      [ -d ${HOME}/.local/share/man/man1 ] || {
        mkdir -p ${HOME}/.local/share/man/man1
      }
      [ -f "${LINMAN}/man1/kitty.1" ] && {
        ln -s "${LINMAN}/man1/kitty.1" ~/.local/share/man/man1/
      }
    }
    [ -d ~/.local/share/man/man5 ] || mkdir -p ~/.local/share/man/man5
    [ -f ~/.local/share/man/man5/kitty.conf.5 ] || {
      [ -d ${HOME}/.local/share/man/man5 ] || {
        mkdir -p ${HOME}/.local/share/man/man5
      }
      [ -f "${LINMAN}/man5/kitty.conf.5" ] && {
        ln -s "${LINMAN}/man5/kitty.conf.5" ~/.local/share/man/man5/
      }
    }
    # Place the kitty.desktop file somewhere it can be found by the OS
    [ -d ~/.local/share/applications ] || mkdir -p ~/.local/share/applications
    [ -f "${HOME}/${LOCAL}/share/applications/kitty.desktop" ] && {
      [ -f ~/.local/share/applications/kitty.desktop ] || {
        cp ~/${LOCAL}/share/applications/kitty.desktop \
          ~/.local/share/applications/
      }
    }
    # If you want to open text files and images in kitty via your file manager
    # also add the kitty-open.desktop file
    [ -f "${HOME}/${LOCAL}/share/applications/kitty-open.desktop" ] && {
      [ -f ~/.local/share/applications/kitty-open.desktop ] || {
        cp ~/${LOCAL}/share/applications/kitty-open.desktop \
          ~/.local/share/applications/
      }
    }
    # Update the paths to the kitty and its icon in the kitty.desktop file(s)
    for desktop in "${HOME}"/.local/share/applications/kitty*.desktop; do
      [ "${desktop}" == "${HOME}/.local/share/applications/kitty*.desktop" ] && continue
      [ -f ${HOME}/${LOCAL}/share/icons/hicolor/256x256/apps/kitty.png ] && {
        sed -i "s|Icon=kitty|Icon=${HOME}/${LOCAL}/share/icons/hicolor/256x256/apps/kitty.png|g" "${desktop}"
      }
      [ -x ${HOME}/${LOCAL}/bin/kitty ] && {
        sed -i "s|Exec=kitty|Exec=${HOME}/${LOCAL}/bin/kitty|g" "${desktop}"
      }
    done
    printf " done!\n"
  else
    printf "\n${BOLD}ERROR:${NORM} Download of kitty installation script failed"
    printf "\nSee https://sw.kovidgoyal.net/kitty/binary/#manually-installing"
    printf "\nto manually install the kitty terminal emulator\n"
  fi

  # Install the Kitty terminfo entry
  KITERM="${HOME}/.terminfo/x/xterm-kitty"
  MATERM="${HOME}/.terminfo/78/xterm-kitty"
  [ -f "${KITERM}" ] || [ -f "${MATERM}" ] || {
    [ -d ${HOME}/.terminfo ] || mkdir -p ${HOME}/.terminfo
    [ -d ${HOME}/.terminfo/x ] || mkdir -p ${HOME}/.terminfo/x
    [ -d ${HOME}/.terminfo/78 ] || mkdir -p ${HOME}/.terminfo/78
    have_tic=$(type -p tic)
    [ "${have_tic}" ] && {
      [ -f "${HOME}/${LOCAL}/lib/kitty/terminfo/kitty.terminfo" ] && {
        tic -x -o ${HOME}/.terminfo \
          "${HOME}/${LOCAL}/lib/kitty/terminfo/kitty.terminfo" >/dev/null 2>&1
      }
    }
    [ -f "${KITERM}" ] || [ -f "${MATERM}" ] || {
      if [ -f "${HOME}/${LOCAL}/lib/kitty/terminfo/x/xterm-kitty" ]; then
        cp "${HOME}/${LOCAL}/lib/kitty/terminfo/x/xterm-kitty" "${KITERM}"
      else
        if [ -f "${HOME}/${LOCAL}/share/terminfo/x/xterm-kitty" ]; then
          cp "${HOME}/${LOCAL}/share/terminfo/x/xterm-kitty" "${KITERM}"
        else
          printf "\nUnable to create Kitty terminfo entry ${KITERM}\n"
        fi
      fi
    }
  }
}

prompt_continue() {
  printf "\nPress <Enter> to continue ... "
  read -r yn
}

set_haves() {
  have_fzf=$(type -p fzf)
  have_figlet=$(type -p figlet)
  have_lolcat=$(type -p lolcat)
  have_rich=$(type -p rich)
}

show_figlet() {
  if [ "$1" ]; then
    FIG_TEXT="$1"
  else
    FIG_TEXT="Kitty Control"
  fi
  # Seed random generator
  RANDOM=$$$(date +%s)
  USE_FONT=${fonts[$RANDOM % ${#fonts[@]}]}
  [ "${USE_FONT}" ] || USE_FONT="Standard"
  if [ "${have_lolcat}" ]; then
    figlet -c -d "${FONTDIR}" -f "${USE_FONT}" -k -t ${FIG_TEXT} 2>/dev/null | ${LOLCAT}
  else
    figlet -c -d "${FONTDIR}" -f "${USE_FONT}" -k -t ${FIG_TEXT} 2>/dev/null
  fi
}

show_usage() {
  clear
  brief_usage noexit
  prompt_continue
}

show_menu() {
  help=
  set_haves
  while true; do
    clear
    if [ "${have_figlet}" ]; then
      show_figlet
    else
      [ "${have_rich}" ] && rich "[cyan]Kitty Control Menu[/cyan]" -p -a rounded -c -C
    fi
    options=()
    PS3="${BOLD}Enter a choice (number, shortcut, or text, 'h' help): ${NORM}"
# Usage: kitty-control [-a] [-c command] [-e] [-i /path/to/image]
# [-m|t <match>] [-s /path/to/socket] [-u|h|v] [back <color>]
# [diff [opts] <path1> <path2>] [fore <color>] [font [num]] [load [subdir]]
# [icat [opts] <image>] [title <title>] [tran [opacity]] [unicode]
# 
#  display several examples run 'kitty-control -e'
#  a full usage message run 'kitty-control -u'
#  a full usage message with examples run 'kitty-control -h'
    options+=("Dark/Opaque" "List Current Info" "Transparent" "Toggle Fullscreen")
    options+=("Select Theme" "Terminal Info" "Unicode Input" "Show Usage Message")
    options+=("Quit (q)")
    select opt in "${options[@]}"; do
      case "$opt,$REPLY" in
      "h",* | *,"h" | "H",* | *,"H" | "help",* | *,"help" | "Help",* | *,"Help")
        printf "\n"
        show_help
        help=1
        break
        ;;
      "Dark/Opaque",* | *,"Dark/Opaque")
        set-opacity "1.0"
        break
        ;;
      "List Current Info",* | *,"List Current Info")
        kitty @ ${SOCKET} ls ${OPTS} | less
        break
        ;;
      "Select Theme",* | *,"Select Theme")
        kitty +kitten themes
        break
        ;;
      "Terminal Info",* | *,"Terminal Info")
        kitty +kitten query_terminal
        break
        ;;
      "Transparent",* | *,"Transparent")
        set-opacity "${OPACITY}"
        break
        ;;
      "Toggle Fullscreen",* | *,"Toggle Fullscreen")
        toggle-fullscreen
        sleep 2
        break
        ;;
      "Unicode Input",* | *,"Unicode Input")
        kitty +kitten unicode_input
        break
        ;;
      "Show Usage Message",* | *,"Show Usage Message")
        show_usage
        break
        ;;
      "Kitty Control Manual"*,* | *,"Kitty Control Manual"*)
        printf "\n"
        man kitty-control
        break
        ;;
      "Check for Updates",* | *,"Check for Updates")
        printf "\nChecking for available updates to Lazyman installed configs\n\n"
        if [ "${have_rich}" ]; then
          check_updates rich
        else
          check_updates
          printf "\n"
        fi
        prompt_continue
        break
        ;;
      "Quit"*,* | *,"Quit"* | "quit"*,* | *,"quit"* | "q",* | *,"q")
        printf "\nExiting kitty-control\n"
        exit 0
        ;;
      *,*)
        printf "\nCould not match '${REPLY}' with a menu entry."
        printf "\nPlease try again with an exact match.\n"
        break
        ;;
      esac
      REPLY=
    done
  done
  [ "${help}" ] && show_main_menu
}

[ "$1" ] || brief_usage

# Some actions need to be delayed until after any configuration load
bg_image=
backgrnd=
foregrnd=
fontplus=
fontdown=
fontsize=
fullscrn=
kittycmd=
setopcty=
while [[ $1 ]]; do
  case "$1" in
    -a | --all)
      OPTS="$OPTS -a"
      shift
      ;;
    -c | --command)
      kittycmd="$2"
      shift 2
      ;;
    -i | --image)
      bg_image="$2"
      shift 2
      ;;
    -f | --fullscreen)
      fullscrn=1
      shift
      ;;
    -m | --match)
      if [ "$2" == "--help" ]; then
        printf "\nSee https://sw.kovidgoyal.net/kitty/remote-control/#matching-windows-and-tabs\n\n"
        exit 0
      else
        OPTS="$OPTS -m $2"
      fi
      shift 2
      ;;
    -s | --socket)
      if [ "$2" == "--help" ]; then
        printf "\nStart kitty as:"
        printf "\n\tkitty -o allow_remote_control=yes --listen-on unix:/tmp/mykitty"
        printf "\nThe kitty '--listen-on' option tells kitty to listen for control messages"
        printf "\nat the specified UNIX-domain socket. See kitty --help for details.\n"
        printf "\nNow you can control this instance of kitty using the"
        printf "\n\tkitten @ --to command line argument to kitten @. For example:"
        printf "\n\tkitten @ --to unix:/tmp/mykitty ls"
        printf "\nRemote control via a socket can be enabled in kitty.conf by setting:"
        printf "\n\tallow_remote_control yes"
        printf "\n\tlisten_on unix:/tmp/mykitty\n"
        printf "\nTo use this with kitty-control invoke with '-s /tmp/mykitty'."
        printf "\nFor example: kitty-control -s /tmp/mykitty fontsize 24"
        printf "\nThis would send the font size command to the Kitty instance"
        printf "\nlistening on the unix domain socket at /tmp/mykitty\n\n"
        exit 0
      else
        [ -S "$2" ] && SOCKET="--to unix:$2"
      fi
      shift 2
      ;;
    -t | --tab)
      if [ "$2" == "--help" ]; then
        printf "\nSee https://sw.kovidgoyal.net/kitty/remote-control/#matching-windows-and-tabs\n\n"
        exit 0
      else
        OPTS="$OPTS -t $2"
      fi
      shift 2
      ;;
    -e | --examples)
      show_examples
      shift
      ;;
    -h | --help)
      usage examples
      shift
      ;;
    -u | --usage)
      usage
      shift
      ;;
    -v | --version)
      printf "\nkitty-control version ${VERSION} release ${RELEASE}\n\n"
      exit 0
      ;;
    back*|--back*)
      if [ "$2" ]; then
        backgrnd="$2"
        shift 2
      else
        printf "\nERROR: background keyword requires an argument"
        brief_usage
      fi
      ;;
    fore*|--fore*)
      if [ "$2" ]; then
        foregrnd="$2"
        shift 2
      else
        printf "\nERROR: foreground keyword requires an argument"
        brief_usage
      fi
      ;;
    diff|--diff)
      if [ "$2" ] && [ "$3" ]; then
        kitty +kitten diff $2 $3
        shift 3
      else
        printf "\nERROR: diff keyword requires two file or directory arguments"
        brief_usage
      fi
      ;;
    icat|--icat)
      if [ "$2" ]; then
        kitty +kitten icat $2
        shift 2
      else
        printf "\nERROR: icat keyword requires an image as argument"
        brief_usage
      fi
      ;;
    list|ls|--list|--ls)
      kitty @ ${SOCKET} ls ${OPTS}
      shift
      ;;
    load|reload|--load|--reload)
      if [ "$2" ]; then
        if [ "$2" == "--help" ]; then
          printf "\nThe 'kitty-control load <subdir>' command loads the Kitty configuration"
          printf "\nfile in '~/.config/kitty/<subdir>/kitty.conf'. The current instance of"
          printf "\nkitty continues to run and the specified configuration file is loaded."
          printf "\nAll tabs and state are preserved while the new configuration is loaded."
          printf "\n\nThe new Kitty configuration file must be prepared beforehand and located"
          printf "\nin the specified subdirectory in the Kitty configuration folder."
          printf "\n\nFor example, if you have one Kitty configuration used for a large screen"
          printf "\nTV and another used for a laptop then placing the TV Kitty configuration"
          printf "\nin ~/.config/kitty/tv/kitty.conf and the laptop Kitty configuration in"
          printf "\n~/.config/kitty/laptop/kitty.conf would allow you to switch between these"
          printf "\ntwo Kitty configurations with kitty-control as follows:"
          printf "\n\tkitty-control load tv # When your display is the TV as monitor"
          printf "\n\tkitty-control load laptop # When you're using the laptop built-in display"
          printf "\n\nTo restore the Kitty configuration in ~/.config/kitty/kitty.conf:"
          printf "\n\tkitty-control load default\n\n"
          exit 0
        else
          if [ -f "${CONFDIR}/$2/kitty.conf" ]; then
            kitty @ ${SOCKET} kitten read_config.py "${CONFDIR}/$2/kitty.conf"
            shift 2
          else
            if [ "$2" == "default" ]; then
              kitty @ ${SOCKET} kitten read_config.py "${CONFDIR}/kitty.conf"
              shift 2
            else
              printf "\n ${CONFDIR}/$2/kitty.conf does not exist\n"
              shift 2
            fi
          fi
        fi
      else
        kitty @ ${SOCKET} kitten read_config.py "${CONFDIR}/kitty.conf"
        shift
      fi
      ;;
    dark|opaque|--dark|--opaque)
      setopcty="1.0"
      shift
      ;;
    fontmin*|fontdec*|--fontmin*|--fontdec*)
      if [ "$2" ]; then
        fontdown="$2"
        shift 2
      else
        fontdown=1
        shift
      fi
      ;;
    fontplus|fontinc*|--fontplus|--fontinc*)
      if [ "$2" ]; then
        fontplus="$2"
        shift 2
      else
        fontplus=1
        shift
      fi
      ;;
    font*|--font*)
      if [ "$2" ]; then
        fontsize="$2"
        shift 2
      else
        fontsize="0"
        shift
      fi
      ;;
    menu|--menu)
      show_menu
      shift
      ;;
    title|--title)
      if [ "$2" ]; then
        kitty @ ${SOCKET} set-tab-title ${OPTS} "$2"
        shift 2
      else
        printf "\nERROR: title keyword requires an argument"
        brief_usage
      fi
      ;;
    opacity|tran*|--opacity|--tran*)
      if [ "$2" ]; then
        OPACITY="$2"
        shift 2
      else
        shift
      fi
      setopcty="${OPACITY}"
      ;;
    term*|--term*)
      kitty +kitten query_terminal
      shift
      ;;
    theme*|--theme*)
      kitty +kitten themes
      shift
      ;;
    unicode|--unicode)
      kitty +kitten unicode_input
      shift
      ;;
    upgrade|--upgrade)
      install_kitty
      shift
      ;;
    *)
      printf "\nUnsupported Kitty control command: $1"
      usage
      ;;
  esac
done

# These needed to be delayed until after any configuration loading
[ "${fontplus}" ] && kitty-fontplus "${fontplus}"
[ "${fontdown}" ] && kitty-fontminus "${fontdown}"
[ "${fontsize}" ] && kitty-fontsize "${fontsize}"
[ "${backgrnd}" ] && set-background "${backgrnd}"
[ "${foregrnd}" ] && set-foreground "${foregrnd}"
[ "${fullscrn}" ] && toggle-fullscreen
[ "${setopcty}" ] && set-opacity "${setopcty}"
[ "${bg_image}" ] && {
  if [ "${bg_image}" == "none" ]; then
    kitty @ ${SOCKET} set-background-image ${OPTS} "${bg_image}"
  else
    if [ -f "${bg_image}" ]; then
      kitty @ ${SOCKET} set-background-image ${OPTS} "${bg_image}"
    else
      printf "\nSpecified Kitty background image ${bg_image} not found\n"
    fi
  fi
}
[ "${kittycmd}" ] && kitty @ ${SOCKET} ${kittycmd} ${OPTS}
