#!/bin/bash

SCRIPT_PATH="$( cd "$(dirname "$0")" ; pwd -P )"
SCRIPT_PATH="$(realpath "$SCRIPT_PATH")"
KITTCONF="${HOME}/.config/kitty"
KCDIR="${KITTCONF}/kitty-control"
DIFFCONF="${KITTCONF}/diff.conf"
DIRDCONF="${KITTY_CONFIG_DIRECTORY}/diff.conf"

rloc=$(readlink ${HOME}/.local/bin/rich)
[ "${rloc}" == "${KCDIR}/.venv/bin/rich" ] && {
  rm -f ${HOME}/.local/bin/rich
}
rm -f ${HOME}/.local/bin/kitty-control
rm -rf ${KCDIR}
find ${KITTCONF} -name kc_read_config.py -print0 | xargs -0 rm -f
[ -f ${DIFFCONF} ] && {
  grep kitty-control ${DIFFCONF} | grep example >/dev/null && {
    rm -f ${DIFFCONF}
  }
}
[ "${KITTY_CONFIG_DIRECTORY}" ] && {
  [ "${KITTY_CONFIG_DIRECTORY}" == "${KITTCONF}" ] || {
    [ -d "${KITTY_CONFIG_DIRECTORY}" ] && {
      rm -rf ${KITTY_CONFIG_DIRECTORY}/kitty-control
      find ${KITTY_CONFIG_DIRECTORY} -name kc_read_config.py -print0 | xargs -0 rm -f
      [ -f ${DIRDCONF} ] && {
        grep kitty-control ${DIRDCONF} | grep example >/dev/null && {
          rm -f ${DIRDCONF}
        }
      }
    }
  }
}
rm -f ${HOME}/.local/share/man/man1/kitty-control*
APP_TOP="${HOME}"/.local/share/applications/kitty-session.desktop
[ -f "${SCRIPT_PATH}"/kitty-session.desktop ] && {
  [ -f "${APP_TOP}" ] && {
    diff "${SCRIPT_PATH}"/kitty-session.desktop "${APP_TOP}" >/dev/null && {
      rm -f "${APP_TOP}"
    }
  }
}
SES_DIR="${HOME}/.config/kitty/sessions"
for start in startup startup-bash; do
  [ -f "${SCRIPT_PATH}"/config/sessions/${start} ] && {
    [ -f "${SES_DIR}"/${start} ] && {
      diff "${SCRIPT_PATH}"/config/sessions/${start} "${SES_DIR}"/${start} >/dev/null && {
        rm -f "${SES_DIR}"/${start}
      }
    }
  }
done

FDEST="${HOME}/.local/share/figlet-fonts"
for ff in "${SCRIPT_PATH}"/figlet-fonts/*
do
  [ "${ff}" == "${SCRIPT_PATH}/figlet-fonts/*" ] && continue
  bn=$(basename "${ff}")
  [ -f "${FDEST}/${bn}"  ] || continue
  diff "${ff}" "${FDEST}/${bn}" > /dev/null && {
    rm -f "${FDEST}/${bn}"
  }
done

empty=1
for i in "${FDEST}"/*
do
  [ "$i" == "${FDEST}/*" ] && continue
  empty=
done
[ "${empty}" ] && {
  [ -d "${FDEST}" ] && rmdir "${FDEST}"
}

# Restore ugly Kitty icons
darwin=
platform=$(uname -s)
[ "${platform}" == "Darwin" ] && darwin=1
if [ "${darwin}" ]; then
  APP="/Applications/kitty.app/Contents/Resources/kitty/logo"
  icon="${APP}"/kitty.png
  SUDO=
  [ -w "${APP}" ] || SUDO="sudo"
  [ -f ${icon}.bak ] && {
    ${SUDO} cp ${icon}.bak ${icon}
    ${SUDO} rm -f ${icon}.bak
  }
  icon="${APP}/kitty-128.png"
  [ -f ${icon}.bak ] && {
    ${SUDO} cp ${icon}.bak ${icon}
    ${SUDO} rm -f ${icon}.bak
  }
else
  APP="${HOME}/.local/kitty.app"
  for icon in ${APP}/lib/kitty/logo/kitty.png \
              ${APP}/share/icons/hicolor/256x256/apps/kitty.png
  do
    [ -f ${icon}.bak ] && {
      cp ${icon}.bak ${icon}
      rm -f ${icon}.bak
    }
  done
  icon="${APP}/lib/kitty/logo/kitty-128.png"
  [ -f ${icon}.bak ] && {
    cp ${icon}.bak ${icon}
    rm -f ${icon}.bak
  }
fi

printf "Removal of kitty-control complete\n\n"
