#!/bin/bash

SCRIPT_PATH="$( cd "$(dirname "$0")" ; pwd -P )"
SCRIPT_PATH="$(realpath "$SCRIPT_PATH")"
DIFFCONF="${HOME}/.config/kitty/diff.conf"
DIRDCONF="${KITTY_CONFIG_DIRECTORY}/diff.conf"

rm -f ${HOME}/.local/bin/kitty-control
rm -f ${HOME}/.config/kitty/read_config.py
rm -rf ${HOME}/.config/kitty/kitty-control
[ -f ${DIFFCONF} ] && {
  grep kitty-control ${DIFFCONF} | grep example >/dev/null && {
    rm -f ${DIFFCONF}
  }
}
[ "${KITTY_CONFIG_DIRECTORY}" ] && {
  [ "${KITTY_CONFIG_DIRECTORY}" == "${HOME}/.config/kitty" ] || {
    [ -d "${KITTY_CONFIG_DIRECTORY}" ] && {
      rm -f ${KITTY_CONFIG_DIRECTORY}/read_config.py
      rm -rf ${KITTY_CONFIG_DIRECTORY}/kitty-control
      [ -f ${DIRDCONF} ] && {
        grep kitty-control ${DIRDCONF} | grep example >/dev/null && {
          rm -f ${DIRDCONF}
        }
      }
    }
  }
}
rm -f ${HOME}/.local/share/man/man1/kitty-control*

FDEST="${HOME}/.local/share/figlet-fonts"
for ff in "${SCRIPT_PATH}"/figlet-fonts/*
do
  [ "${ff}" == "${SCRIPT_PATH}/figlet-fonts/*" ] && continue
  bn=$(basename "${ff}")
  [ -f "${FDEST}/${bn}"  ] || continue
  diff "${ff}" "${FDEST}/${bn}" > /dev/null && {
    rm -f "${FDEST}/${bn}"
  }
done

empty=1
for i in "${FDEST}"/*
do
  [ "$i" == "${FDEST}/*" ] && continue
  empty=
done
[ "${empty}" ] && rmdir "${FDEST}"

printf "Removal of kitty-control complete\n\n"
